<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TME</RootNamespace>
    <LangVersion>9</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.3.2" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scenario\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Types\" />
    <Folder Include="Scenario\Default\" />
    <Folder Include="Scenario\Default\Scenario\" />
    <Folder Include="Serialize\" />
  </ItemGroup>
</Project>
