using System;

namespace TME.Scenario.Default.Flags
{
    [Flags]
    public enum LordQualities : ulong
    {
        None                = 0,
        // +ve
        Brave               = 1UL << 0,
        FarSighted          = 1UL << 1,
        Selfless            = 1UL << 2,
        Bold                = 1UL << 3,
        Kind                = 1UL << 4,
        WarmHearted         = 1UL << 5,
        Gentle              = 1UL << 6,
        Generous            = 1UL << 7,
        QuickWitted         = 1UL << 8,
        Talkative           = 1UL << 9,
        HomeLoving          = 1UL << 10,
        Eager               = 1UL << 11,
        Energetic           = 1UL << 12,
        Tireless            = 1UL << 13,
        Modest              = 1UL << 14,
        Passionate          = 1UL << 15,
        Reliable            = 1UL << 16,
        Gallant             = 1UL << 17,
        Charming            = 1UL << 18,
        Loyal               = 1UL << 19,
        Gregarious          = 1UL << 20,
        Peaceable           = 1UL << 21,
        Polite              = 1UL << 22,
        Submissive          = 1UL << 23,
        Patient             = 1UL << 24,
        LevelHeaded         = 1UL << 25,
        Persuasive          = 1UL << 26,
        Knowledgeable       = 1UL << 27,
        Naive               = 1UL << 28,
        HotTempered         = 1UL << 29,
        MightyWarrior       = 1UL << 30,
        SuperbLeader        = 1UL << 31,
// -ve
        Cowardly            = 1UL << 32,
        Reckless            = 1UL << 33,
        Selfish             = 1UL << 34,
        Cautious            = 1UL << 35,
        Cruel               = 1UL << 36,
        ColdHearted         = 1UL << 37,
        Vicious             = 1UL << 38,
        Greedy              = 1UL << 39,
        SlowWitted          = 1UL << 40,
        TightLipped         = 1UL << 41,
        Restless            = 1UL << 42,
        Apathetic           = 1UL << 43,
        Languid             = 1UL << 44,
        EasilyTired         = 1UL << 45,
        Arrogant            = 1UL << 46,
        Passionless         = 1UL << 47,
        Headstrong          = 1UL << 48,
        Malicious           = 1UL << 49,
        Repulsive           = 1UL << 50,
        Treacherous         = 1UL << 51,
        Solitary            = 1UL << 52,
        Bloodthirsty        = 1UL << 53,
        Provocative         = 1UL << 54,
        Domineering         = 1UL << 55,
        Impatient           = 1UL << 56,
        Mad                 = 1UL << 57,
        Unconvincing        = 1UL << 58,
        Ignorant            = 1UL << 59,
        Sceptical           = 1UL << 60,
        ThickSkinned        = 1UL << 61,
        FeebleWarrior       = 1UL << 62,
        PitifulLeader       = 1UL << 63,
    }
}
